name: atomparser
version: 0.0.1
description: Atom feed parser.
authors:
  - Ashish Acharya <anarchyrucks@gmail.com>
homepage: https://github.com/anarchyrucks/atomparser

environment:
  sdk: ">=1.24.3 <2.0.0"

dependencies:
  xml: "^3.0.0"

dev_dependencies:
  test: "^0.12.32+1"
